// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrkgau5xyzqME3wjZ0S1PmMYKNoqxQS5k',
    appId: '1:642181655311:web:190d4630943879c91f6c7a',
    messagingSenderId: '642181655311',
    projectId: 'cryptoapp-da8c1',
    authDomain: 'cryptoapp-da8c1.firebaseapp.com',
    storageBucket: 'cryptoapp-da8c1.firebasestorage.app',
    measurementId: 'G-P2S5Y2X3E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMYO-bY4FYhvvdMnDk1i-1gQuxB_ffdnc',
    appId: '1:642181655311:android:2fa0dac9d6b3b7311f6c7a',
    messagingSenderId: '642181655311',
    projectId: 'cryptoapp-da8c1',
    storageBucket: 'cryptoapp-da8c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuDCCMwjOubHGshXQrrhXAKLxGyHca8yg',
    appId: '1:642181655311:ios:66ee12a316a9f4611f6c7a',
    messagingSenderId: '642181655311',
    projectId: 'cryptoapp-da8c1',
    storageBucket: 'cryptoapp-da8c1.firebasestorage.app',
    iosBundleId: 'com.example.cryptoimmobilierapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuDCCMwjOubHGshXQrrhXAKLxGyHca8yg',
    appId: '1:642181655311:ios:66ee12a316a9f4611f6c7a',
    messagingSenderId: '642181655311',
    projectId: 'cryptoapp-da8c1',
    storageBucket: 'cryptoapp-da8c1.firebasestorage.app',
    iosBundleId: 'com.example.cryptoimmobilierapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrkgau5xyzqME3wjZ0S1PmMYKNoqxQS5k',
    appId: '1:642181655311:web:a5ccc2b0173151491f6c7a',
    messagingSenderId: '642181655311',
    projectId: 'cryptoapp-da8c1',
    authDomain: 'cryptoapp-da8c1.firebaseapp.com',
    storageBucket: 'cryptoapp-da8c1.firebasestorage.app',
    measurementId: 'G-BDH4TCL27P',
  );
}
